import type { Config } from 'tailwindcss'
import animate from 'tailwindcss-animate'

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#380038',
        'on-secondary-fixed-variant': '#810081',
        'background': '#131313',
        'inverse-primary': '#006970',
        'on-tertiary': '#283500',
        'error': '#ffb4ab',
        'on-secondary': '#5b005b',
        'on-tertiary-fixed-variant': '#3c4d00',
        'inverse-on-surface': '#313030',
        'surface-container': '#201f1f',
        'surface': '#131313',
        'surface-tint': '#00dbe9',
        'on-primary': '#00363a',
        'primary-container': '#00f0ff',
        'surface-bright': '#3a3939',
        'surface-container-low': '#1c1b1b',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#ffabf3',
        'tertiary': '#e9ffa8',
        'on-surface-variant': '#b9cacb',
        'primary-fixed': '#7df4ff',
        'outline': '#849495',
        'tertiary-fixed': '#c3f400',
        'on-primary-fixed-variant': '#004f54',
        'on-surface': '#e5e2e1',
        'on-secondary-container': '#500050',
        'secondary-container': '#fe00fe',
        'surface-variant': '#353534',
        'secondary': '#ffabf3',
        'tertiary-container': '#bbea00',
        'primary': '#dbfcff',
        'inverse-surface': '#e5e2e1',
        'tertiary-fixed-dim': '#abd600',
        'on-tertiary-fixed': '#161e00',
        'primary-fixed-dim': '#00dbe9',
        'on-background': '#e5e2e1',
        'outline-variant': '#3b494b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-primary-container': '#006970',
        'on-error-container': '#ffdad6',
        'on-tertiary-container': '#506600',
        'secondary-fixed': '#ffd7f5',
        'on-primary-fixed': '#002022',
        'surface-dim': '#131313',
        'surface-container-lowest': '#0e0e0e',
        'on-error': '#690005',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [animate],
}

export default config
